<?xml version="1.0" ?>
<testsuites>
	<testsuite errors="1" failures="0" name="74196337-84be-463d-9a07-1212c69242ec" skipped="0" tests="1" time="0.00001">
		<properties>
			<property name="OS" value="Linux 4.4.0-66-generic #87-Ubuntu SMP Fri Mar 3 15:29:05 UTC 2017 x86_64"/>
			<property name="Platform" value="UnknownPlatform, VID: 8086, DID: 7190"/>
			<property name="CHIPSEC" value="1.2.5"/>
		</properties>
		<testcase classname="chipsec.modules.smm" name="chipsec.modules.smm" time="0.00001">
			<error message="Exception occurred during chipsec.modules.smm.run(): 'No module named smm'" type="error"/>
			<system-out>ERROR: Exception occurred during import of chipsec.modules.smm: 'No module named smm'
[-] Traceback (most recent call last):
  File &quot;/home/soheil/Desktop/iust/chipsec/chipsec/module.py&quot;, line 55, in do_import
    self.module = importlib.import_module( self.name )
  File &quot;/usr/lib/python2.7/importlib/__init__.py&quot;, line 37, in import_module
    __import__(name)
ImportError: No module named smm

[-] Traceback (most recent call last):
  File &quot;../gui_api.py&quot;, line 208, in run_module
    if not modx.do_import(): return ModuleResult.ERROR
  File &quot;/home/soheil/Desktop/iust/chipsec/chipsec/module.py&quot;, line 61, in do_import
    raise msg
ImportError: No module named smm

ERROR: Exception occurred during chipsec.modules.smm.run(): 'No module named smm'
</system-out>
		</testcase>
	</testsuite>
</testsuites>
